apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: iot-server-demo-streamer
  name: iot-server-demo-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iot-server-demo-streamer
  template:
    metadata:
      labels:
        run: iot-server-demo-streamer
    spec:
      containers:
      - name: iot-server-demo-streamer
        image: navicore/iot-server-demo
        imagePullPolicy: Always
        env:
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: AKKA_SEED0
          value: "akka.tcp://IotServerDemo@iot-server-demo-seed-0.iot-server-demo-seed:2551"
        - name: AKKA_SEED1
          value: "akka.tcp://IotServerDemo@iot-server-demo-seed-1.iot-server-demo-seed:2551"
        - name: BOOTSTRAP
          value: "kafka-0.broker.kafka.svc.cluster.local:9092"
        - name: CONSUMER_GROUP
          value: "IotDemoServerStreamer"
        - name: ROLE
          value: "streamer"
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
